.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

/* Handwritten function */
nonmatching entrypoint, 0x54

glabel entrypoint
    /* 1000 80000400 3C1D803F */  lui        $sp, (0x803FFFC0 >> 16)
    /* 1004 80000404 37BDFFC0 */  ori        $sp, $sp, (0x803FFFC0 & 0xFFFF)
    /* 1008 80000408 3C08800C */  lui        $t0, %hi(main_BSS_START)
    /* 100C 8000040C 25082000 */  addiu      $t0, $t0, %lo(main_BSS_START)
    /* 1010 80000410 3C09800F */  lui        $t1, %hi(main_BSS_END)
    /* 1014 80000414 25293730 */  addiu      $t1, $t1, %lo(main_BSS_END)
    /* 1018 80000418 11090005 */  beq        $t0, $t1, .L80000430
    /* 101C 8000041C 00000000 */   nop
  .L80000420:
    /* 1020 80000420 25080004 */  addiu      $t0, $t0, 0x4
    /* 1024 80000424 0109502B */  sltu       $t2, $t0, $t1
    /* 1028 80000428 1540FFFD */  bnez       $t2, .L80000420
    /* 102C 8000042C AD00FFFC */   sw        $zero, -0x4($t0)
  .L80000430:
    /* 1030 80000430 2404001E */  addiu      $a0, $zero, 0x1E
  .L80000434:
    /* 1034 80000434 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
    /* 1038 80000438 40840000 */  mtc0       $a0, $0 /* handwritten instruction */
    /* 103C 8000043C 3C098000 */  lui        $t1, (0x80000000 >> 16)
    /* 1040 80000440 40895000 */  mtc0       $t1, $10 /* handwritten instruction */
    /* 1044 80000444 40801000 */  mtc0       $zero, $2 /* handwritten instruction */
    /* 1048 80000448 40801800 */  mtc0       $zero, $3 /* handwritten instruction */
    /* 104C 8000044C 00000000 */  nop
    /* 1050 80000450 42000002 */  tlbwi /* handwritten instruction */
endlabel entrypoint
    /* 1054 80000454 00000000 */  nop
    /* 1058 80000458 00000000 */  nop
    /* 105C 8000045C 00000000 */  nop
    /* 1060 80000460 00000000 */  nop
